sudo: required
services:
- docker
before_script:
- mkdir /etc/docker/ -p
- touch /etc/docker/daemon.json
- echo "{\"insecure-registries\":[\"${DOCKER_SERVER}\"]}" > /etc/docker/daemon.json
- systemctl docker restart
script:
- docker-compose build
- echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_SERVER} --username "${DOCKER_USERNAME}" --password-stdin
- docker tag microservicedemo/identityserver ${DOCKER_SERVER}/microservicedemo/identityserver
- docker push ${DOCKER_SERVER}/microservicedemo/identityserver
- docker tag microservicedemo/api_gateway ${DOCKER_SERVER}/microservicedemo/api_gateway
- docker push ${DOCKER_SERVER}/microservicedemo/api_gateway
- docker tag microservicedemo/dotnet_service ${DOCKER_SERVER}/microservicedemo/dotnet_service
- docker push ${DOCKER_SERVER}/microservicedemo/dotnet_service
- docker tag microservicedemo/node_service ${DOCKER_SERVER}/microservicedemo/node_service
- docker push ${DOCKER_SERVER}/microservicedemo/node_service
- docker tag microservicedemo/spa_client ${DOCKER_SERVER}/microservicedemo/spa_client
- docker push ${DOCKER_SERVER}/microservicedemo/spa_client